---

- name: Create directories for the scripts to write into
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: 0o700
  loop: openvpn_script_output_directories

- name: Create scripts directory
  file:
    path: "{{ openvpn_scripts_dir }}"
    state: directory

- name: Upload script files
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_scripts_dir }}"
    mode: 0o744
  loop: "{{ openvpn_script_files }}"

- name: Upload inline scripts
  copy:
    content: "{{ item.content }}"
    dest: "{{ openvpn_scripts_dir }}/{{ item.name }}"
    mode: 0o744
  loop: "{{ openvpn_inline_scripts }}"
