---

- name: Install firewall dependencies (Debian)
  apt:
    name: "{{ packages }}"
  when: ansible_os_family == "Debian"
  vars:
    packages:
      - iptables
      - iptables-persistent
      - module-init-tools

- name: Read existing iptable rules
  shell: iptables -L
  tags:
    # Ansible Lint complains about using shell instead of the iptables_module
    - skip_ansible_lint
  register: iptables_rules
  changed_when: false

- name: Read existing iptable rules (nat table)
  shell: iptables -L -t nat
  tags:
    # Ansible Lint complains about using shell instead of the iptables_module
    - skip_ansible_lint
  register: iptables_nat_rules
  changed_when: false

- name: Allow connections to the OpenVPN server
  iptables:
    chain: INPUT
    in_interface: "{{ openvpn_out_interface | default(omit, true) }}"
    ctstate: NEW
    protocol: udp
    destination_port: "{{ openvpn_port }}"
    jump: ACCEPT
    comment: incoming_openvpn
  notify: openvpn save iptables
  when: iptables_rules.stdout.find("incoming_openvpn") == -1
