---

- name: Check if crl list exists
  stat:
    path: >-
      {{
        openvpn_keydir + '/crl.pem' if openvpn_crl_mode == 'file' else
        openvpn_keydir + '/revoked/certs_by_serial/'
      }}
  register: _openvpn_crl_exists

- name: Create crl directory
  file:
    path: "{{ openvpn_etcdir }}/crl/"
    state: directory

- name: Copy crl list
  copy:
    src: >-
      {{
        openvpn_keydir + '/crl.pem' if openvpn_crl_mode == 'file' else
        openvpn_keydir + '/revoked/certs_by_serial'
      }}
    dest: "{{ openvpn_etcdir }}/crl/"
    remote_src: true
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
  when: _openvpn_crl_exists.stat.exists | bool
